// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgreeBtn: typeof import('./src/components/common/home-content-unit/AgreeBtn.vue')['default']
    AnswerOperate: typeof import('./src/components/common/home-content-unit/AnswerOperate.vue')['default']
    AvatarInfo: typeof import('./src/components/common/AvatarInfo.vue')['default']
    CommentSection: typeof import('./src/components/common/home-content-unit/CommentSection.vue')['default']
    CommentUnit: typeof import('./src/components/common/home-content-unit/CommentUnit.vue')['default']
    Default: typeof import('./src/components/home/Default.vue')['default']
    DisagreeBtn: typeof import('./src/components/common/home-content-unit/DisagreeBtn.vue')['default']
    Edit: typeof import('./src/components/people/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    Follow: typeof import('./src/components/home/Follow.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    HomeContentUnit: typeof import('./src/components/common/home-content-unit/HomeContentUnit.vue')['default']
    Hot: typeof import('./src/components/home/Hot.vue')['default']
    Index: typeof import('./src/components/home/Index.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    NewQuestionModal: typeof import('./src/components/common/NewQuestionModal.vue')['default']
    Notification: typeof import('./src/components/common/Notification.vue')['default']
    People: typeof import('./src/components/people/People.vue')['default']
    PrivateMessage: typeof import('./src/components/common/PrivateMessage.vue')['default']
    QAndAContent: typeof import('./src/components/common/home-content-unit/QAndAContent.vue')['default']
    Question: typeof import('./src/components/question/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/people/Setting.vue')['default']
    Sider: typeof import('./src/components/common/Sider.vue')['default']
    UserCenterMore: typeof import('./src/components/common/UserCenterMore.vue')['default']
    Video: typeof import('./src/components/home/Video.vue')['default']
  }
}

export {}
