// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AgreeBtn: typeof import('./components/common/home-content-unit/AgreeBtn.vue')['default']
    AnswerOperate: typeof import('./components/common/home-content-unit/AnswerOperate.vue')['default']
    AvatarInfo: typeof import('./components/common/AvatarInfo.vue')['default']
    CommentSection: typeof import('./components/common/home-content-unit/CommentSection.vue')['default']
    CommentUnit: typeof import('./components/common/home-content-unit/CommentUnit.vue')['default']
    Default: typeof import('./components/home/Default.vue')['default']
    DisagreeBtn: typeof import('./components/common/home-content-unit/DisagreeBtn.vue')['default']
    Edit: typeof import('./components/people/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ExploreSection: typeof import('./components/explore/ExploreSection.vue')['default']
    Follow: typeof import('./components/home/Follow.vue')['default']
    Header: typeof import('./components/common/Header.vue')['default']
    HomeContentUnit: typeof import('./components/common/home-content-unit/HomeContentUnit.vue')['default']
    Hot: typeof import('./components/home/Hot.vue')['default']
    Index: typeof import('./components/home/Index.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    Login: typeof import('./components/login/Login.vue')['default']
    NewQuestionModal: typeof import('./components/common/NewQuestionModal.vue')['default']
    Notification: typeof import('./components/common/Notification.vue')['default']
    People: typeof import('./components/people/People.vue')['default']
    PrivateMessage: typeof import('./components/common/PrivateMessage.vue')['default']
    QAndAContent: typeof import('./components/common/home-content-unit/QAndAContent.vue')['default']
    Question: typeof import('./components/question/Question.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./components/people/Setting.vue')['default']
    Sider: typeof import('./components/common/Sider.vue')['default']
    UserCenterMore: typeof import('./components/common/UserCenterMore.vue')['default']
    Video: typeof import('./components/home/Video.vue')['default']
    VIPRankItem: typeof import('./components/VIP/VIPRankItem.vue')['default']
  }
}

export {}
